title: Portafolio de Sistemas Operativos
description: Prácticas del curso de Sistemas Operativos - UTM
author: Natalia
lang: es

collections:
  temas:
    output: true
    permalink: /temas/:path/

defaults:
  - scope:
      path: "_temas"
      type: temas
    values:
      layout: post
  - scope:
      path: "_temas/01-introduccion-linux/index.md"
      type: temas
    values:
      layout: tema
  - scope:
      path: "_temas/02-procesos-hilos/index.md"
      type: temas
    values:
      layout: tema
  - scope:
      path: "_temas/03-ipc/index.md"
      type: temas
    values:
      layout: tema
  - scope:
      path: "_temas/05-administracion-memoria/index.md"
      type: temas
    values:
      layout: tema
  - scope:
      path: "_temas/06-sistema-archivos/index.md"
      type: temas
    values:
      layout: tema
  - scope:
      path: "_temas/07-senales/index.md"
      type: temas
    values:
      layout: tema
